menu:
  #Archives: /archives
  #项目作品: /projects
  #关于我: /aboutme
#rss: /atom.xml
social:
  weibo: http://weibo.com/jk2K
  segmentfault:
  github: https://github.com/jk2K
  stack_overflow: http://stackoverflow.com/users/2227031/jk2k
  facebook:
  twitter:
  google_plus:

page_comment: true
disqus_shortname: jk2K
logo: /images/logo.jpg
background:
  cover: /images/background-cover.jpg
  color: cover-blue

archive_date_format: MMM DD
fancybox: true

google_analytics: UA-63739663-1
favicon: /images/logo.jpg
